"""add_mcp_hardening_fields

Revision ID: 4575cb94e281
Revises: ee280bc27e49
Create Date: 2025-12-08 17:49:09.020842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4575cb94e281'
down_revision: Union[str, Sequence[str], None] = 'ee280bc27e49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('systemsetting',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('agentknowledgefile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('chatsession', sa.Column('total_tokens', sa.Integer(), nullable=False))
    op.add_column('chatsession', sa.Column('prompt_tokens', sa.Integer(), nullable=False))
    op.add_column('chatsession', sa.Column('completion_tokens', sa.Integer(), nullable=False))
    op.add_column('mcpserver', sa.Column('command', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('mcpserver', sa.Column('args', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('mcpserver', sa.Column('cwd', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('mcpserver', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('mcpserver', sa.Column('last_heartbeat', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('mcpserver', sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('mcpserver', sa.Column('checksum', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('mcpserver', sa.Column('size_bytes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mcpserver', 'size_bytes')
    op.drop_column('mcpserver', 'checksum')
    op.drop_column('mcpserver', 'last_error')
    op.drop_column('mcpserver', 'last_heartbeat')
    op.drop_column('mcpserver', 'status')
    op.drop_column('mcpserver', 'cwd')
    op.drop_column('mcpserver', 'args')
    op.drop_column('mcpserver', 'command')
    op.drop_column('chatsession', 'completion_tokens')
    op.drop_column('chatsession', 'prompt_tokens')
    op.drop_column('chatsession', 'total_tokens')
    op.drop_table('agentknowledgefile')
    op.drop_table('systemsetting')
    # ### end Alembic commands ###
